// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_DJIGZVpATlp7ZfmpsmD7NvbNv5zumpU',
    appId: '1:68147761419:web:49c8601d9b0c1e4be2120e',
    messagingSenderId: '68147761419',
    projectId: 'wedding-invitation-utility',
    authDomain: 'wedding-invitation-utility.firebaseapp.com',
    storageBucket: 'wedding-invitation-utility.appspot.com',
    measurementId: 'G-6T1TJCXB1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTABcqeIHoQds-iow1eNx6mzMdTmlngU',
    appId: '1:68147761419:android:c112db971166ca5ae2120e',
    messagingSenderId: '68147761419',
    projectId: 'wedding-invitation-utility',
    storageBucket: 'wedding-invitation-utility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhet3WsM1KUGjXYh6Dh-ar34WOXK3y_A',
    appId: '1:68147761419:ios:46f27443b5c89154e2120e',
    messagingSenderId: '68147761419',
    projectId: 'wedding-invitation-utility',
    storageBucket: 'wedding-invitation-utility.appspot.com',
    iosBundleId: 'com.example.invitationMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuhet3WsM1KUGjXYh6Dh-ar34WOXK3y_A',
    appId: '1:68147761419:ios:46f27443b5c89154e2120e',
    messagingSenderId: '68147761419',
    projectId: 'wedding-invitation-utility',
    storageBucket: 'wedding-invitation-utility.appspot.com',
    iosBundleId: 'com.example.invitationMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_DJIGZVpATlp7ZfmpsmD7NvbNv5zumpU',
    appId: '1:68147761419:web:8bde0506997cf2e3e2120e',
    messagingSenderId: '68147761419',
    projectId: 'wedding-invitation-utility',
    authDomain: 'wedding-invitation-utility.firebaseapp.com',
    storageBucket: 'wedding-invitation-utility.appspot.com',
    measurementId: 'G-03CXKKHZD6',
  );
}
